[package]
name = "modrinth-bulk"
version = "0.1.0"
edition = "2021"

[dependencies]

reqwest = { version = "0.11.12", features = ["blocking", "json"] }
serde = { version = "1.0.147", features = ["derive"] }
serde_json = "1.0"
